export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-heading text-2xl font-semibold">Terms of Service</h1>
      <p className="mt-2 text-sm text-[var(--color-text-secondary)]">
        Last updated: March 18, 2026
      </p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-[var(--color-text-secondary)]">
        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            1. Acceptance of Terms
          </h2>
          <p>
            By installing the Agents For X browser extension or using the
            Agents For X dashboard, you agree to these Terms of Service. If
            you do not agree, please uninstall the extension and discontinue
            use of the service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            2. Description of Service
          </h2>
          <p>
            Agents For X provides tools to help you create content on X
            (Twitter), including:
          </p>
          <ul className="mt-2 list-disc space-y-1.5 pl-6">
            <li>Saving posts as inspiration and pattern references.</li>
            <li>AI-generated reply suggestions based on post context.</li>
            <li>
              Opportunity scoring to identify high-value engagement
              opportunities.
            </li>
            <li>
              Analytics and content management via the web dashboard.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            3. Acceptable Use
          </h2>
          <p>You agree not to use Agents For X to:</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-6">
            <li>
              Violate X&apos;s Terms of Service or any applicable law.
            </li>
            <li>
              Automate posting, liking, following, or other bulk actions on X.
              The extension assists with reply composition only; you retain
              full control over what is posted.
            </li>
            <li>
              Harass, spam, or mislead other users on X.
            </li>
            <li>
              Reverse-engineer, decompile, or attempt to extract the source
              code of the service&apos;s server-side components.
            </li>
            <li>
              Share your account credentials with others or allow
              unauthorised access to your account.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            4. AI-Generated Content
          </h2>
          <p>
            Reply suggestions generated by Agents For X are produced by AI
            models and are provided as drafts for your review.{" "}
            <strong>
              You are solely responsible for any content you choose to post on
              X.
            </strong>{" "}
            We do not guarantee that AI-generated replies will be accurate,
            appropriate, or free from errors. Always review generated content
            before posting.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            5. API Usage &amp; Rate Limits
          </h2>
          <p>
            The service relies on server-side APIs for reply generation and
            data storage. We reserve the right to impose rate limits or
            throttle usage to maintain service quality. Excessive or abusive
            API usage may result in temporary or permanent suspension of your
            account.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            6. Availability &amp; Changes
          </h2>
          <p>
            We strive to keep the service available but do not guarantee
            uninterrupted access. Features may be added, modified, or removed
            at any time. We will make reasonable efforts to notify users of
            significant changes.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            7. Intellectual Property
          </h2>
          <p>
            You retain ownership of any content you create or save using
            Agents For X. We retain ownership of the software, branding, and
            AI models. By submitting feedback on generated replies, you grant
            us a non-exclusive licence to use that feedback to improve the
            service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            8. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by law, Agents For X is provided
            &quot;as is&quot; without warranties of any kind. We shall not be
            liable for any indirect, incidental, or consequential damages
            arising from your use of the service, including but not limited to
            any actions taken on X based on AI-generated suggestions.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            9. Termination
          </h2>
          <p>
            We may suspend or terminate your access to the service at our
            discretion if you violate these terms. You may stop using the
            service and uninstall the extension at any time.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[var(--color-text-primary)]">
            10. Contact
          </h2>
          <p>
            For questions about these terms, email us at{" "}
            <a
              href="mailto:support@agentsforx.com"
              className="text-[var(--color-text-primary)] underline"
            >
              support@agentsforx.com
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
